spring:
    application:
        name: freezeout-server
    datasource:
        url:
        username:
        password:
        driver-class-name: oracle.jdbc.driver.OracleDriver
    profiles:
        jwt:
            secret:

mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml

server:
    port: 80
